### ISSUE TITLE
When will the conditional inference code be released?

### ISSUE THREAD

**Issue by elisha0904** [jaepoong/PosterLlama#1]
Many thanks for the great work!

I am in need of the conditional inference code and would like to inquire about the specific timeline for its release.
Could you please let me know when it is expected to be available?

Thank you.

**Comment by fx-hit** [comment]
I also encountered the same issue. I tried using the `build_input( canvas_width, canvas_height, vals)` function in generation.py to construct conditional prompts and found it to be feasible. For example, using the 'image' and 'type' conditions, `vals` can be constructed as `['logo', None, None, None, None]`.

**Comment by elisha0904** [comment]
> I also encountered the same issue. I tried using the `build_input( canvas_width, canvas_height, vals)` function in generation.py to construct conditional prompts and found it to be feasible. For example, using the 'image' and 'type' conditions, `vals` can be constructed as `['logo', None, None, None, None]`.

Thank you very much. I will also give it a try.

**Comment by jaepoong** [comment]
Thank you for your interest in my research. 
Unfortunately, I am currently overwhelmed with work and unable to make progress now. 
I have full code but just needs to be organized, so I will release it as soon as possible, likely by mid-August.
