### ISSUE TITLE
Question about <M> token

### ISSUE THREAD

**Issue by miridih-jyjang** [jaepoong/PosterLlama#3]
Hi, Thanks for fanstastic work!
I saw that your code doesn't use Mask Token since tokenizer has None for mask_token.
However, as seen in the convert_html folder, you use <M> token as Mask token. How could it be accepted as Mask token to the pretrained tokenizer & model?

Thanks in advance

**Comment by miridih-jyjang** [comment]
<img width="238" alt="image" src="https://github.com/user-attachments/assets/ef40170c-1e6d-4250-9a0b-b6f4ffaa0d37">

**Comment by jaepoong** [comment]
Thank you for your interest. In our research, we utilized the text as-is without adding any additional special tokens to the tokenizer. The text formatting is applied in the form of SPAN_MASK_TOKEN="<M>", as shown in the link below.
https://github.com/jaepoong/PosterLlama/blob/b75ae38b9cb6e24bd25f5a612ab01c2b2570fcba/convertHTML/build_code_jj2.py#L35
