### ISSUE TITLE
The  LAMA processing script or dataset

### ISSUE THREAD

**Issue by yinglang** [jaepoong/PosterLlama#5]
That's a very nice work! I want to know if the clean image after LAMA processing will be opened, or the processing script will be opened, I need to train on my dataset, so the processing script is essential for me. It will be much helpful if the script is available. Much looking forward for your response.

**Comment by jaepoong** [comment]
Thank you for interesting about our work.
I added the processed dataset samples on 
[dataset](https://drive.google.com/drive/folders/1OK7O4h_JxaEVzm5Jlb2YrsKjwYmHfKNv?usp=sharing)
After unzip dataset, you change config.train_img_path, config.val_img_path, config.train_json, config.val_json at src/common/configs_stage2_dino_codellama.py to your unzipped path.

**Comment by yinglang** [comment]
Thanks very much！That's much helpful for me. By the way, is this processing done by directly taking the bounding boxes of all "text", "underlay", "logo" and "embellishment" as the mask input for LAMA?

**Comment by yinglang** [comment]
Much Thanks!!! i got it.
