### ISSUE TITLE
About test code

### ISSUE THREAD

**Issue by wd1511** [jaepoong/PosterLlama#9]
Hello, what are the functions of demo.ipynb, eval.py, generation.py, generate.py, and text_translation.py respectively when I am testing. I now have a test_numerical.jsonl and corresponding images. How can I test it on the test data set?

**Comment by jaepoong** [comment]
Thank you for interesting.
The demo.ipynb is just sampling code when you have your custom poster image.
Another is not important for testing.

After making the test html code and image following Readme instruction.
You could generate on CGL or PKU dataset using generate.py code.
I updated the sampling code.
